### ISSUE TITLE
Access to the prediction results on the test set

### ISSUE THREAD

**Issue by nooralahzadeh** [baeseongsu/ehrxqa#10]
Hi,
We want to compare the results from our method to the results that you have in the test set.
Is there any possibility of sharing the output of your method on the test set?

Thanks,
Farhad

**Comment by baeseongsu** [comment]
Hi, @nooralahzadeh 

Do you want the experimental results for the executed NeuralSQL (i.e., the answer itself) generated by prompting BM25 (train), which is the third row in Table 5?

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
Hi @baeseongsu 
Thanks for the prompt response. It would be great to have  the generated NeuralSQL and the execution results for ChatGPT+ M3AE (both Fixed and BM25) in the test set!

Best,
Farhad

**Comment by baeseongsu** [comment]
Hi @nooralahzadeh,

I will provide those generated and executed results within this week. I need to double-check whether the results are exactly the same as the ones used in the paper.

Best,
Seongsu

**Comment by baeseongsu** [comment]
Hi @nooralahzadeh,

Sorry for the delayed response :(

I've uploaded the generated NeuralSQL and execution results for ChatGPT + M3AE (both fixed and BM25) in the test dataset via Dropbox link. Here is the link: https://www.dropbox.com/scl/fo/2tuz46h0nv4s4felfuu7j/AC5iaC5ooh4xY0HCR2S8gQc?rlkey=1zsfvkj4jpy3qbbogp3l3g9qk&st=2e14k2zj&dl=0

Note that this is the file I used in the arXiv submission. However, since execution results depend on the syntax in SQL grammar (e.g., "How many days" can be computed as Julian day (float) or just integer), I cannot guarantee 100% identical execution results. Nevertheless, they are very similar to the original experimental results (actually even better because I updated some postprocessing and executor parts after the publication).

If you have any questions about the detailed implementation, please feel free to ask.

**Comment by nooralahzadeh** [comment]
Dear @baeseongsu 
Thanks for your effort and for providing the experiment results.
It is indeed valuable in our work.
I recommend putting a link to this in your GitHub repository to share with other researchers.

Best,
Farhad

**Comment by nooralahzadeh** [comment]
Hi,
Do you have the results for GPT 4o? is there any chance to have them?

Thanks,
Farhad

**Comment by baeseongsu** [comment]
Hi @nooralahzadeh,

I do not have any results for GPT-4o at the moment, but if I have time to work on this, I will share the results for GPT-4o.

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
Hi @baeseongsu 
Thanks for the quick reply, May I ask you when you will be able to provide it? We selected 100 examples from the test set and would like the result of GPT-4o with a temperature = 0 on them. If I share them, would it be possible to have the results by early next week?

here is the list of these 100 examples: https://docs.google.com/spreadsheets/d/1KxgnCpkpA80Hz5yO2i_0W1ba9_dKXsQc4oDIDgEKYBI/edit?gid=799116924#gid=799116924

Thanks, Farhad

**Comment by baeseongsu** [comment]
Hi, @nooralahzadeh 

To clarify your request: You need evaluation results for only the 100 samples listed in the Google Sheets, using gpt-4o-2024-08-06 as Text-to-Query parser and incorporating the visual module as the M3AE model we used in the main experiment. Is that correct?

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
Yes, same as you did before but with GPT.4o

**Comment by baeseongsu** [comment]
Hi @nooralahzadeh,

I can provide the results by early next week (expected: 12/10). Is that okay for you?

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
It would be great. Thanks

**Comment by nooralahzadeh** [comment]
Hi @baeseongsu , 
will the result be available tomorrow?  I appreciate your effort.

Best,
Farhad

**Comment by baeseongsu** [comment]
@nooralahzadeh Yes, I will let you know once I’m finished within today.

**Comment by baeseongsu** [comment]
@nooralahzadeh Here are the `gpt-4o-2024-08-06` using bm25 retrieval strategy results I’ve quickly reviewed: https://docs.google.com/spreadsheets/d/1BiMUnU04YJuv0NwTLYBR_mQfmGht9nDrs1JI28cukTA/edit?usp=sharing

Overall, the execution scores are 37/100 (for the GT NeuralSQL query) and 38/100 (for the predicted NeuralSQL query).

Note: This is a different NeuralSQL executor that I created compared to the current arXiv version, so the prediction scores are slightly different. Compared to the previous ChatGPT models, I ran the same procedure with a different model tag (gpt-3.5-turbo-0125) and obtained the following scores: 36/100 (for the GT NeuralSQL query) and 36/100 (for the predicted NeuralSQL query). When filtered with the arXiv file (which I’ve uploaded to Dropbox) results using the same ID, the execution results are 42/100 (for the GT NeuralSQL query).

If you have any questions, please let me know.

Best, 
Seongsu

**Comment by nooralahzadeh** [comment]
Dear @baeseongsu 
Thanks a lot for providing the results. How did you calculate the execution scores as 37/100? you may have a column/columns that show this comparison but are hidden in the shared Excel file!

Thanks,
Farhad

**Comment by nooralahzadeh** [comment]
Hi @baeseongsu 
Is it possible to have this result without a few-shot setup? Our system is doing the task in zero-shot setup and we also want to compare to your result in zero-shot setting.
Thanks

**Comment by baeseongsu** [comment]
Hi, @nooralahzadeh 

I used exact matching accuracy after post-processing the answers but did not include the individual match results in the Google Sheet.
I can provide zero-shot setting results. I believe the zero-shot prompt should include basic information such as schema details. Does this zero-shot strategy align with your needs, or do you have any additional information that should be included in the zero-shot prompt?

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
Hi @baeseongsu ,
Thanks for your reply and explanation of the evaluation process. We also did the similar to have the accuracy.
Regarding the zero-shot what I require is the result without including 15 examples using BM25. you can keep the other setup as it is: such as schema!

Best,
Farhad

**Comment by baeseongsu** [comment]
Hi @nooralahzadeh,

I will first try the zero-shot approach with the schema, as it is a necessary and natural condition. Please note that there is a chance the zero-shot results (with schema information) could outperform the few-shot results using BM25 (10 examples, without schema information).

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
Hi @baeseongsu 
What do you mean with Schema? Are you going to provide all the DB info or only the related Tabels considering the question?
Please be aware that I would like the first approach, giving all DB schema and let the model find the related tables and columns! 
Best,
Farhad

**Comment by baeseongsu** [comment]
@nooralahzadeh Providing only complete database information (tables and columns) as context, without additional hints such as related tables based on the questions. I have created another sheet page in the same Google Sheet link and then uploaded the entire zero-shot results. For the evaluation, the overall score for the zero-shot results generated by the gpt-4o-2024-08-06 model is 0/100. I believe there are two main issues: (1) my current instruction prompt is not well-structured, causing the generated queries to be disorganized; and (2) since my executor does not fully support the NeuralSQL format, it cannot obtain an answer even if the query is correct.
If you have any further questions, please let me know.

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
Thanks a lot. 
Could you provide your code base and how to run with GPT4o for us? In case we want to re-run it!
And please let me know if you performed all the experiments using the visual module as the M3AE model!

Best,
Farhad

**Comment by baeseongsu** [comment]
Hi @nooralahzadeh,

For the entire NeuralSQL pipeline, including the parsing and execution stages, please refer to this directory: https://github.com/baeseongsu/ehrxqa/tree/dev-experiment/experiment/NeuralSQL.
I used the visual module as the M3AE model for all experiments.

Best,
Seongsu
