### ISSUE TITLE
CSV meanings in Database

### ISSUE THREAD

**Issue by ghost** [baeseongsu/ehrxqa#12]
Dear author:
       Thanks for this wonderful work. I would like to ask about the meaning of the 18 CSV files in the database. Could you please explain what each one represents?

**Comment by dek924** [comment]
Hello, @tianjiedai.

Thank you for your inquiry. Regarding the 18 CSV files in the database, 17 come from MIMIC-IV and 1 from MIMIC-CXR. The files from MIMIC-IV include tables such as admissions, chartevents, cost, d_icd_diagnoses, d_icd_procedures, d_items, d_labitems, diagnoses_icd, icustays, inputevents, labevents, microbiologyevents, outputevents, patients, prescriptions, procedures_icd, and transfers. The single file from MIMIC-CXR is tb_cxr, which serves as a bridge between patient records and their corresponding chest X-ray images stored in the MIMIC-CXR-JPG image database.

For more detailed information about the database, please visit our [project page](https://physionet.org/content/ehrxqa/1.0.0/#:~:text=214%20(4.5%25)-,Files%20and%20Structure,-We%20introduce%20two) on PhysioNet.

Best,
Daeun
