### ISSUE TITLE
the categories for modality-base (Image, Table, Image+Table) and patient-based scope (none, single, group)

### ISSUE THREAD

**Issue by nooralahzadeh** [baeseongsu/ehrxqa#6]
Hello,

Thanks for this great work.
I wonder if any identifiers in the dataset indicate the categories for modality-base (Image, Table, Image+Table) and patient-based scope (none, single, group)?

Thanks

**Comment by baeseongsu** [comment]
Hi @nooralahzadeh ,

Currently, we do not support direct identifiers in the dataset. However, you can try using the code from these links:

1. https://github.com/baeseongsu/ehrxqa/blob/724bff13a9a2e430ecd54f32e3ef3789bb7fcdb3/tests/test_utils.py#L45-L67
2. https://github.com/baeseongsu/ehrxqa/blob/724bff13a9a2e430ecd54f32e3ef3789bb7fcdb3/tests/test_utils.py#L132-L148

You can filter the dataset using the `scope` argument. The possible values for the scope are:

- TABLE-NONE
- TABLE-SINGLE
- TABLE-GROUP
- IMAGE-SINGLE-1
- IMAGE-SINGLE-2
- IMAGE-SINGLE-N
- IMAGE-GROUP-N
- MULTIMODAL-SINGLE
- MULTIMODAL-GROUP

The `scope` argument uses string matching at the start, so you can also use broader categories like "IMAGE-SINGLE" or "IMAGE-GROUP" (or even "IMAGE") to include all relevant subcategories.

Sorry for the inconvenience.

Best,
Seongsu

**Comment by nooralahzadeh** [comment]
Thanks.
