### ISSUE TITLE
Is there a sample demo? I still don't know how to run it！

### ISSUE THREAD

**Issue by sheng2616** [baeseongsu/ehrxqa#9]
Thanks for your hard work. Do you have a sample demo? Once installed, it still won't be used. What does the UI look like?

**Comment by baeseongsu** [comment]
Hi, @sheng2616 !

We do not currently support any sample demo with a specific UI here and mainly support the dataset itself.
However, if you want to try our proposed NeuralSQL method, please refer to [here](https://github.com/baeseongsu/ehrxqa/tree/dev-experiment/experiment/NeuralSQL).
Sorry for the inconvenience, and thank you for asking about the demo.

Best,
Seongsu
